### ISSUE TITLE
Clarify Approach

### ISSUE THREAD

**Issue by SeanPedersen** [jmward01/lmplay#3]
Hey,
this looks very interesting but the README fails to clearly communicate the core idea for me.

- What is the main idea behind this (in few clear sentences)?
- How do you improve on traditional embedding models like a ResNet (trained on ImageNet) or Transformer (for next token prediction)?
- How do you treat low frequency training data differently?

**Comment by jmward01** [comment]
I see the confusion. The repo is mainly intended to allow me to quickly test different ideas and compare the results so it is agnostic to the actual experiments. I probably need to simplify the readme and break out individual pages for the different experiments to make things a bit more clear. 

As for the main idea behind UE, the two sentence 'what it does' is improve embedding training by adding a sacrificial network at train time that is removed for prod inference. The result is a much better trained model with exactly the same structure at inferrence since the sacrificial network is removed and standard static embeddings are then calculated making the weights 100% the same stucture as a non UE trained model. Bottom line, during training just swap the embedding used to UE and you will see a very large improvement in model training. See the 'try it' section in the readme.

The 'why it works' is just a theory. I added a write-up on my theory of 'token drag' to the main readme.

I'll think about re-structuring the readme to make the split between the repo and the experiments a bit more clear.

**Comment by jmward01** [comment]
Does the new format help a bit? I'm not the best writer :) Lemme know if you have more suggestions to make things more clear.
